[package]
name = "izumi-elo"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
dirs = "5.0.1"
inquire = "0.7.5"
rand = "0.8.5"
ron = "0.8.1"
serde = { version = "1.0.209", features = ["derive"] }
